name: Deploy to DreamHost

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DREAMHOST_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.DREAMHOST_HOST }} >> ~/.ssh/known_hosts

    - name: Set up Node.jobs
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install Dependencies
      run: npm ci

    - name: Build Eleventy site
      run: npm run build

    - name: Deploy to DreamHost via rsync
      run: |
        rsync -rlpgoDvz --checksum --exclude=".git" --exclude=".github" --exclude="README.md" ./_site ${{secrets.DREAMHOST_USER }}@${{ secrets.DREAMHOST_HOST }}:${{ secrets.DREAMHOST_REMOTE_PATH }}

      